apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  labels:
    app: crypto-recommendation-service
  name: crypto-recommendation-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: crypto-recommendation-service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: crypto-recommendation-service
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.activeProfile }}
          image: cryptorecommendation:1.0.0
          imagePullPolicy: Never
          name: crypto-recommendation-service
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  labels:
    app: crypto-recommendation-service
  name: crypto-recommendation-service
spec:
  type: LoadBalancer
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: crypto-recommendation-service