spring:
  application:
    name: "Crypto Recommendation Service"
  profiles:
    active: "dev"
  cache:
    cache-names:
      - rate-limit
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s

springdoc:
  api-docs:
    path: /api-docs

crypto:
  directory: "classpath:assets/prices"

application:
  pom:
    version: $project.version$
    name: $project.name$
    description: $project.description$

#rate limit settings based on IP address
bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit
      hide-http-response-headers: false
      url: /api/.*
      filter-method: servlet
      rate-limits:
        - expression: "getRemoteAddr()"
          bandwidths:
            - capacity: 5
              time: 10
              unit: seconds
